### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by f3l1x** [fmasa/auto-di#2]
Hi. Great extension by the way. 👍  What do you think about joint it to Contributte organization? Well, you know, there's already contributte/di with `ResourceExtension`, which does pretty same stuff. But I must say, wildcard matching is missing.

https://github.com/contributte/di/blob/master/.docs/README.md#resourceextension

 WDYT? :-)

**Comment by fmasa** [comment]
Hi, thank you for offer. I have several other features in mind and I am already running this extension on several projects. So I have to pass for now, but I definitely consider it in future before next major version. :slightly_smiling_face:
