### ISSUE TITLE
Order of extensions

### ISSUE THREAD

**Issue by dakorpar** [fmasa/auto-di#4]
It would maybe be worth to mention that is really important to see on which place you'll register autoDI extension.
For example if U're using AOP extension autoDI has to be after it.
If U're using Kdyby events make sure autoDI is before them otherwise events won't run and U will have serious complications.

@fmasa can U also please put that in documentation and make important note for it? It's really very important

**Comment by fmasa** [comment]
This is related to #3.

I'll definitely mention it in docs.
Problems are caused by registering services in `beforeCompile` instead of `loadConfiguration` in order to exclude already registered classes.

By AOP you mean [Kdyby/Aop](https://github.com/Kdyby/Aop)? What is the problem there? Maybe we can find some solution.

**Comment by dakorpar** [comment]
Yes, I'm thinking on Kdyby/AOP, actually my fork of it with minimal adjustements to make it work with new versions since kdyby repositories are sadly dead...
When I put autoDI before aop extension services were registered correctly for first few loads and then everything crashed, it randomly couldn't find services at all. My best guess is that it happens after first class with aop annotations code is being runned and aop generates proxy classes.

**Comment by dakorpar** [comment]
Actually, forget previous comment, I'm still investigating it, I had big issues when seeing that events didn't work on production and then it was pure panic and just doing something to make it work, at one point I put autoDI to first place as extension and first few loads were ok, and then everything crashed because services couldn't be found. When I deleted temp/cache dir everything was ok again for few loads and then same story (I believe error was that 'Kdyby\Aop_CG\Container_...Services couldn't be found) . On test server I did not catch that since we're using events in few specific cases, and our unit tests don't cover that. But definitivelly something I must look into and put some code that will kill all aplication if anything fails, I did it already for events, I rather kill whole app now if I notice events are not running, because yesterday was really really bad.

**Comment by dakorpar** [comment]
Looks like autoDI is not compatible at all with aop.
If I put aop before autoDI then aop doesn't work if I put autoDI after it, then everything crashed when I load page which uses some service that uses AOP, and then whole app fails because proxy services couldn't be found...  'Kdyby\Aop_CG\Container_...Services couldn't be found) 
I'm able to reproduce this only on linux server, not on my local machine running windows

**Comment by fmasa** [comment]
@dakorpar Hi, I just released [version 1.1](https://github.com/fmasa/auto-di/releases/tag/1.1) which allows registration of services in earlier phase of DIC lifecycle. Does it solve the issue for you?

If not, can you provide minimal example for reproduction?

Thank you.

**Comment by dakorpar** [comment]
Will do it in few weeks, to buisy atm.

**Comment by dakorpar** [comment]
I've tried with this option and looks like it's working now.
sorry for delay

**Comment by fmasa** [comment]
No problem, thank you for confirmation.
